# Generated by Django 4.1.2 on 2022-11-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="class_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
