# Generated by Django 4.1.2 on 2022-11-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0004_alter_user_address"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Subjects",
                to="custom_users.teacher",
            ),
        ),
    ]
