# Generated by Django 4.1.2 on 2022-11-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0001_initial"),
        ("custom_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="grades.grade"
            ),
        ),
    ]
